<!-- Footer -->
	<footer class="bg-primary" style="background-color:#1b1b1b;">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-12 text-center">
					<H4><strong>find us on</strong></h4>					
					<ul class="list-inline">
						<li><div class="smcontainer">
							<a href="https://www.facebook.com/comdotty" target="_blank" rel="noopener" aria-label="ComDotty on Facebook"><div class="cube">
								<div class="side back facebook">
									<i class="fab fa-facebook-f icon"></i>
								</div>
								<div class="side left grey">
									<i class="fab fa-facebook-f icon"></i>
								</div>
								<div class="side front grey">
									<i class="fab fa-facebook-f icon smcolor"></i>
								</div>
								<div class="side right grey">
									<i class="fab fa-facebook-f icon"></i>
								</div>
								<div class="side top grey">
									<i class="fab fa-facebook-f icon"></i>
								</div>
								<div class="side bottom grey">
									<i class="fab fa-facebook-f icon"></i>
								</div>
							</div></a>
						</div></li>
						<li><div class="smcontainer">
							<a href="https://goo.gl/maps/9rJcugEt9YC2" target="_blank" rel="noopener" aria-label="ComDotty on Google+"><div class="cube">
								<div class="side back googleplus">
									<i class="fab fa-google-plus-g icon"></i>
								</div>
								<div class="side left grey">
									<i class="fab fa-google-plus-g icon"></i>
								</div>
								<div class="side front grey">
									<i class="fab fa-google-plus-g icon smcolor"></i>
								</div>
								<div class="side right grey">
									<i class="fab fa-google-plus-g icon"></i>
								</div>
								<div class="side top grey">
									<i class="fab fa-google-plus-g icon"></i>
								</div>
								<div class="side bottom grey">
									<i class="fab fa-google-plus-g icon"></i>
								</div>
							</div></a>
						</div></li>
						<li><div class="smcontainer">
							<a href="https://www.linkedin.com/company/comdottywebservices/" target="_blank" rel="noopener" aria-label="ComDotty on LinkedIn"><div class="cube">
								<div class="side back linkedin">
									<i class="fab fa-linkedin-in icon"></i>
								</div>
								<div class="side left grey">
									<i class="fab fa-linkedin-in icon"></i>
								</div>
								<div class="side front grey">
									<i class="fab fa-linkedin-in icon smcolor"></i>
								</div>
								<div class="side right grey">
									<i class="fab fa-linkedin-in icon"></i>
								</div>
								<div class="side top grey">
									<i class="fab fa-linkedin-in icon"></i>
								</div>
								<div class="side bottom grey">
									<i class="fab fa-linkedin-in icon"></i>
								</div>
							</div></a>
						</div></li>
						<li><div class="smcontainer">
							<a href="https://twitter.com/comdottydotcom" target="_blank" rel="noopener" aria-label="ComDotty on Twitter"><div class="cube">
								<div class="side back twitter">
									<i class="fab fa-twitter icon"></i>
								</div>
								<div class="side left grey">
									<i class="fab fa-twitter icon"></i>
								</div>
								<div class="side front grey">
									<i class="fab fa-twitter icon smcolor"></i>
								</div>
								<div class="side right grey">
									<i class="fab fa-twitter icon"></i>
								</div>
								<div class="side top grey">
									<i class="fab fa-twitter icon"></i>
								</div>
								<div class="side bottom grey">
									<i class="fab fa-twitter icon"></i>
								</div>
							</div></a>
						</div></li>
					</ul>
					<hr class="smaller">
					<ul class="list-unstyled">
						<li>
							<i class="fas fa-envelope fa-fw spacer footercopy" aria-hidden="true"></i><a href="mailto:enquiries@comdotty.com" class="footercopy whitelink">enquiries@comdotty.com</a>
						</li>
					</ul>
					<hr class="smaller">
					<p class="text-center footercopy">all content and images</p><p class="text-center footercopy"><i class="far fa-copyright fa-fw"></i>&nbsp;comDotty web services 2018</p>
					<hr class="smaller">
					<p class="text-center footercopy">for robbie.</p>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 text-center">
					<h4>
						<img src="https://resource.comdotty.com/phflag.png" width="32" height="16" class="flagicon flagspacer" alt="Flag of The Republic of the Philippines"><strong>republic of the philippines</strong>
					</h4>
					<p class="footercopy">
						davao city, davao del sur<br>8000
					</p>
					<ul class="list-unstyled">
						<li class="footercopy"><i class="fas fa-phone-square fa-fw spacer" aria-hidden="true"></i>(+63) 919-726-7493</li>
					</ul>
					<br>
					<h4>
						<img src="https://resource.comdotty.com/ukflag.png" width="32" height="16" class="flagicon flagspacer" alt="Flag of the United Kingdom"><strong>united kingdom</strong>
					</h4>
					<p class="footercopy">
						basingstoke, hampshire<br>RG21 7TL
					</p>
					<ul class="list-unstyled">
						<li class="footercopy"><i class="fas fa-phone-square fa-fw spacer" aria-hidden="true"></i>(+44) 7985-156273</li>
					</ul>
					<p class="footercopy">last updated 08/12/2018.</p>					
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 text-center">
					<h4><strong>header animation</strong></h4>
					<p class="footercopy">bislig bay &amp; mangagoy<br>may 2015</p>
					<p class="footercopy">compostella valley<br>june 2015</p>					
					<p class="footercopy">sohoton lagoon, socorro<br>november 2016</p>
					<p class="footercopy">paradise island resort, garden city of samal<br>july 2017</p>
					<p class="footercopy">mindanao, republic of the philippines.</p>
					<br>
				</div>
			</div>
		</div>
		<!-- /.container -->
	</footer>